### ISSUE TITLE
Command crashes homebridge

### ISSUE THREAD

**Issue by quintcaec** [luisiam/homebridge-cmdswitch2#45]
Hi there,

Running a command to control my HarmonyHub, works on a Lubuntu install on a different HarmonyHub, but keeps failing (and crashing Homebridge) on a Raspberry Pi. Checked the logs, only bit of info I could dig up is:

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:380:11)
    at exports.spawn (child_process.js:493:38)
    at Object.exports.execFile (child_process.js:209:15)
    at exports.exec (child_process.js:139:18)
    at cmdSwitchPlatform.setPowerState (/usr/local/lib/node_modules/homebridge-cmdswitch2/index.js:222:3)
    at Characteristic.emit (events.js:160:13)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:320:10)
    at Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:183:32)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-cmdswitch2/index.js:237:12)
    at ontimeout (timers.js:458:11)

**Comment by iGodPhil** [comment]
Same here.
